# Generated by Django 6.0.3 on 2026-05-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_diet_member_workout_delete_user_diet_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='workout_name',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise',
            field=models.CharField(choices=[('Push Ups', 'Push Ups'), ('Pull Ups', 'Pull Ups'), ('Squats', 'Squats'), ('Bench Press', 'Bench Press'), ('Deadlift', 'Deadlift'), ('Bicep Curls', 'Bicep Curls'), ('Running', 'Running'), ('Cycling', 'Cycling')], default='Push Ups', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='calories_burned',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
